<template>
  <div class="text-big">
    <p>De imediato, uma estranheza ou um ruído chega aos ouvidos de quem lê ou ouve. Sim: <strong>Aus Ouvidos</strong>! Uma ideia que emerge em um momento de desassossegos, atritos; em meio a tantas adversidades e particularidades cotidianas, em uma época que exige um estado de felicidade constante, tempo que se avalia por quantidade de curtidas ou visualizações dígito-virtuais. Nesse contexto, muitas vezes o escutar se reduz a breves mensagens de áudios; e a escrita, por sua vez, torna-se, cada vez mais abreviada. Quando, por consequência, as relações e os laços são enfraquecidos, as seguintes questões ecoam: de que forma a escuta se estabelece entre nós e quais os laços que são construídos a partir dela. <strong>Aus Ouvidos</strong> é uma proposta que busca refletir sobre estas questões.</p>
    <p>A exigência de sucesso consome a todos e a cada um em momentos distintos; nosso laser e nossas relações parecem não mais nos pertencer. O abandono de si, diante de tal exigência, é acentuado, quase inevitável, pois parece não haver espaço e tempo para se escutar, escutar e escutar ao outro. A lei bruta de uma felicidade obrigatória, sensação com a qual apenas o sucesso combina, impera para a desconstrução de laços. Não podemos mostrar fragilidade.</p>
    <p>A escuta passa pelo corpo de quem fala e de quem ouve e, assim, sentimentos brotam à flor da pele; sem ela, sentimentos e comportamentos de abandono, de isolamento e solidão convergem em patologias. Sintomas de depressão e o abandono de projetos de vida são mais e mais observados, bem como um aumento significativo no índice de suicídios. Escutar, tarefa complexa, desafiadora, inquieta e instigante, sem dúvida, seria um modo de prevenção.</p>
    <p>A escuta acarreta, concomitantemente, uma fala que provoca e que convoca os corpos a se presentificarem, ainda que virtualmente. Escutar é oferecer um espaço para a fala se recriar, compor comunicar e expressar. É movimentar algo, buscar sintonia e sincronia que promovam laços e ecoem.</p>
    <p><strong>Aus</strong> vem de auscultar, que, na medicina, é o ato de escutar os sons interiores do organismo; propiciador da percepção do funcionamento dos órgãos em sua condição de normalidade ou anomalia. Por meio da expressão: ‘sou todo ouvidos’, ‘ouvidos’ é como nos oferecemos em escuta ao outro, e  <strong>Aus Ouvidos</strong> é uma proposta de escuta que se dá no encontro com o que vem do outro por meio de sua  voz e  expressões que possam narrar angustias, alegrias, duvidas, histórias entre tantas outras possibilidades.</p>
    <p><strong>Aus Ouvidos</strong> parte de uma equipe formada por profissionais que trabalham na construção de uma escuta qualificada para promover a constituição de vínculos fortalecimento de laços com o objetivo primordial de prevenção de suicídios e resgate de vidas. </p>
    <p>Todo o trabalho é metodologicamente desenvolvido por meio de intervenções lúdicas, provocativas e reflexivas, servindo-se das artes cênicas, da palhaçaria e do samba no formato de rodas de conversa. <strong>Aus Ouvidos</strong> é uma iniciativa multidisciplinar que envolve e relaciona <strong>a psicóloga/psicanalista, o palhaço/artista, o educador/pedagogo e sambista</strong> com recursos da arte. Nele, ferramentas cênicas, como a palhaçaria e o samba, apresentam-se para a construção de diálogos e reflexões sobre temas diversos como forma de provocação a partir de uma leitura seguida de uma intervenção psicanalítica e artística tendo em vista envolvimentos pessoais com a escuta.</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Home extends Vue {}
</script>
